name: GCC Version Tests

on:
  push:
    branches: [ main, master, v* ]
  pull_request:
    branches: [ main, master, v* ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gcc-test:
    timeout-minutes: 20
    strategy:
      matrix:
        gcc_version: [4, 5, 8, 9, 10, 11, 12, 13]
        runner: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-22.04-arm]
      fail-fast: false
    
    runs-on: ${{ matrix.runner }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Test GCC ${{ matrix.gcc_version }} on ${{ matrix.runner }}
      run: |
        echo "Testing GCC ${{ matrix.gcc_version }} on ${{ matrix.runner }}"
        docker run -i -v "$PWD:/src" --rm gcc:${{ matrix.gcc_version }} bash -c "cd /src && make clean && make && output/eatmemory 100M -t 0" 